stages:
  - test/build
  - deploy

test/build:
  image: node:10
  stage: test/build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - mvn package -Pprod verify jib:dockerBuild
    - docker push bofgames:latest

deploy:
  image: docker:stable
  script:
    - echo 'It will work one day'


# variables:
#   DOCKER_HOST: "tcp://url:2376"
#   DOCKER_TLS_VERIFY: 1
#   STACK_NAME: bofgames
# script:
#   - mkdir -p ~/.docker
#   - echo "$STAGING_DOCKER_CA" > ~/.docker/ca.pem
#   - echo "$STAGING_DOCKER_CERT" > ~/.docker/cert.pem
#   - echo "$STAGING_DOCKER_KEY" > ~/.docker/key.pem
#   - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
#   - docker stack deploy --with-registry-auth -c docker-compose.yml "$STACK_NAME"
