stages:
  - test
  - build
  - deploy

front_test:
  image: node:10
  stage: test
  before_script:
    - npm install
  script:
    - npm test

front_test_e2e:
  image: node:10
  stage: test
  before_script:
    - npm install
  script:
    - npm run e2e

back_test:
  image: maven:3.6.2-jdk-11-slim
  stage: test
  script:
    - mvn test

build_image:
  image: maven:3.6.2-jdk-11-slim
  stage: build
  script:
    - ./mvnw package -Pprod verify jib:dockerBuild
