version: '2'
services:
  bofgames-app:
    image: registry.gitlab.com/projet-ecom-m2gi/bofgames
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bofgames-postgresql:5432/bofgames
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://bofgames-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bofgames-elasticsearch:9200
    ports:
      - 8080:8080
  bofgames-postgresql:
    extends:
      file: postgresql.yml
      service: bofgames-postgresql
  bofgames-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: bofgames-elasticsearch
