version: '2'
services:
  bofgames-app:
    image: registry.gitlab.com/projet-ecom-m2gi/bofgames
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bofgames-postgresql:5432/bofgames
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://bofgames-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bofgames-elasticsearch:9200
    ports:
      - 8080:8080
  bofgames-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/bofgames/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bofgames
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
  bofgames-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    # volumes:
    #     - ~/volumes/jhipster/bofgames/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
